### ISSUE TITLE
Add support for folders

### ISSUE THREAD

**Issue by dbeaulieu** [mwiedemeyer/SPDeployer#1]
It would be useful to specify all files in a folder, for example:

```xml
<File Path="app\*.js" Destination="SiteAssets/App" />
```

**Comment by mwiedemeyer** [comment]
That would be great. Maybe there is someone who want to add that feature!?

**Comment by mwiedemeyer** [comment]
I've just uploaded [SPDeployment](https://github.com/mwiedemeyer/SPDeployment) which is a command line tool to deploy to SharePoint. You can install it with `npm install spdeployment -g`. It supports folders, so I will not update this VS extension to include folders.
